# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rentoo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rentoo
  pod 'GoogleMaps'

  
  target 'rentooTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rentoo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rentoo-tvOS

  target 'rentoo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
